name: Run test suite for dev
on:
  push:
    branches: [dev]
jobs:
  deploy_source:
    name: Automatically test Dev
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: run test suite for dev
        run: node backend/tests_dev.js
        env:
          CI: true